import React, { useState, Suspense, useEffect } from "react";
import { Form, Input, Button, Row, Col, Spin, Modal, message } from "antd";
import { getPCRStatus, setPCRStatus } from "../../../../services/localServices";
import apiServices from "../../../../services/exportService";
function ChangePassowrd() {
  const [ChangePasswordShow, setChangePasswordShow] = useState(false);
  const handleSubmit = (values) => {
    console.log(values);
    apiServices
      .post("User/change-password/", values)
      .then((data) => {
        message.success("Password Changed Successfully.");
        setPCRStatus("PCR", "false");
        setChangePasswordShow(false);
      })
      .catch(() => {
        message.error("Please try again!");
      });
  };
  useEffect(() => {
    let isPCRState = getPCRStatus();
    if (isPCRState) {
      setChangePasswordShow(true);
    } else {
      setChangePasswordShow(false);
    }
  }, []);

  return (
    <Modal
      centered
      open={ChangePasswordShow}
      footer={null}
      width={400}
      closable={false}
      keyboard={false}
      style={{ padding: "0" }}
    >
      {/* <AuthenticationWrap> */}
      <div className="ninjadash-authentication-wrap">
        <div className="ninjadash-authentication-brand">
          {/* <img src={require(`../../../../static/img/logo_dark.svg`).default} alt="" /> */}
        </div>
        <Row justify="center">
          <Col>
            <Form name="forgotPass" onFinish={handleSubmit} layout="vertical">
              <div className="ninjadash-authentication-top">
                <h2 className="ninjadash-authentication-top__title">
                  Enter New Password
                </h2>
              </div>
              <div className="ninjadash-authentication-content">
                <p className="forgot-text">
                  Update your password as it is generated by the system.
                </p>
                <Form.Item
                  name="password"
                  label="Password"
                  style={{ width: "100%", marginTop: "1vh" }}
                  rules={[
                    {
                      required: true,
                      message: "Please input your password!",
                    },
                  ]}
                  hasFeedback
                >
                  <Input.Password
                    placeholder="Create new password"
                    size="large"
                    style={{ width: "100%" }}
                    allowClear
                  />
                </Form.Item>
                <Form.Item
                  name="confirm_password"
                  label="Confirm Password"
                  dependencies={["password"]}
                  hasFeedback
                  style={{ width: "100%", marginTop: "1vh" }}
                  rules={[
                    {
                      required: true,
                      message: "Please confirm your password!",
                    },
                    ({ getFieldValue }) => ({
                      validator(_, value) {
                        if (!value || getFieldValue("password") === value) {
                          return Promise.resolve();
                        }
                        return Promise.reject(
                          new Error(
                            "The new password that you entered do not match!"
                          )
                        );
                      },
                    }),
                  ]}
                >
                  <Input.Password
                    placeholder="Confirm new password"
                    size="large"
                    style={{ width: "100%" }}
                    allowClear
                  />
                </Form.Item>
                <Form.Item>
                  <Button
                    className="btn-reset"
                    htmlType="submit"
                    type="primary"
                    size="large"
                  >
                    Change Password
                  </Button>
                </Form.Item>
              </div>
            </Form>
          </Col>
        </Row>{" "}
      </div>
      {/* </AuthenticationWrap> */}
    </Modal>
  );
}

export default ChangePassowrd;
